/*
    Code generated by TFMin tensorflow to ansi-c converter.
    Do not edit.
*/
#ifndef __MNIST_MODEL_H__
#define __MNIST_MODEL_H__
#include "mnist_weights.h"

void mnist_model(void *tensor_arena, float *const p_input_47x_45input_580,
                 float *p_Layer2_47activation_580);

#endif /* __MNIST_MODEL_H__ */
