/*
    Code generated by TFMin tensorflow to ansi-c converter.
    Do not edit.
*/
#ifndef __MNIST_WEIGHTS_H__
#define __MNIST_WEIGHTS_H__
#include <inttypes.h>

#define MNIST_TENSOR_ARENA_SIZE 1200 /* size of the tensor area in bytes */

extern const uint32_t mnist_Layer1_47weights_47Variable_47read_580[];
extern const uint32_t mnist_Layer1_47biases_47Variable_47read_580[];
extern const uint32_t mnist_Layer2_47weights_47Variable_47read_580[];
extern const uint32_t mnist_Layer2_47biases_47Variable_47read_580[];

#endif /* __MNIST_WEIGHTS_H__ */
